### ISSUE TITLE
NXThemes

### ISSUE THREAD

**Issue by btc08gh** [StarDustCFW/SoundNX#1]
[SoundNX](https://github.com/StarDustCFW/SoundNX) works with Atmosphere 1.2.2 with no issues.  Upgraded to 1.2.4 and all of a sudden it clashes with [NXThemes](https://github.com/exelix11/SwitchThemeInjector/releases).  My Switch blackscreens after the Nintendo logo unless I remove 010000000000100C (SoundNX) or 0100000000001000 (NXThemes).  Did a completely fresh clean install of 1.2.4 and only installed these two items and can’t boot unless I disable one or the other.  Tried moving SoundNX to 010000000000200C but then it didn’t work anymore.  Any way to get these two apps to play together again?

**Comment by btc08gh** [comment]
Didn’t realize you are the same guy on the Atmosphere thread.  I’ve been digging into this for a while now.  I really want to get this working on 1.2.4 and beyond.

**Comment by Kronos2308** [comment]
i see
so can't be use the 2 
SoundNX is yust a replacement fo the original sounds that use the overlay and that crash

**Comment by Kronos2308** [comment]
but since is just a fs there is no much i can do

**Comment by btc08gh** [comment]
Issue with AMS 1.2.4 not with SoundNX
